import Foundation
import AuthenticationServices

/*Essential PrerequisitesTo make this code work without crash errors, 
you must fulfill these infrastructure tasks:Associated Domains: In Xcode under Signing & Capabilities, 
add the Associated Domains capability. Set it to webcredentials:yourdomain.com.Server Configuration: 
You must host an apple-app-site-association (AASA) file at your server's root domain (https://yourdomain.com). 
It must contain a reference to your app's bundle ID:

{
  "webcredentials": {
    "apps": [ "ABC123XYZ.com.yourcompany.appname" ]
  }
}

*/



/// A thread-safe coordinator that manages Passkey authentication flows.
class PasskeyManager: NSObject {
    
    // MARK: - Properties
    
    /// The WebAuthn Relying Party Identifier (typically your app's verified domain).
    private let domain = "yourdomain.com"
    
    /// A closure to handle the success or failure of the Passkey operation.
    private var completionHandler: ((Result<ASAuthorization, Error>) -> Void)?
    
    // MARK: - Public Interface
    
    /// Registers a new Passkey credential for a user.
    /// - Parameters:
    ///   - username: The user-visible account identifier (e.g., email address).
    ///   - userID: A unique, non-identifiable binary ID generated by your backend for the user.
    ///   - challenge: A cryptographically secure random byte array generated by your server.
    ///   - completion: Returns the authorization details containing the public key credential on success.
    func registerPasskey(username: String, userID: Data, challenge: Data, completion: @escaping (Result<ASAuthorization, Error>) -> Void) {
        self.completionHandler = completion
        
        // 1. Initialize the platform provider for Passkeys
        let provider = ASAuthorizationPlatformPublicKeyCredentialProvider(relyingPartyIdentifier: domain)
        
        // 2. Create the registration request
        let request = provider.createCredentialRegistrationRequest(
            challenge: challenge,
            name: username,
            userID: userID
        )
        
        // 3. (Optional) Configure standard WebAuthn options if supported by your server
        request.attestationPreference = .none
        request.userVerificationPreference = .required
        
        // 4. Initialize and execute the presentation controller
        executeAuthorizationRequest(requests: [request])
    }
    
    /// Performs a login assertion using an existing Passkey.
    /// - Parameters:
    ///   - challenge: A cryptographically secure random byte array generated by your server to prevent replay attacks.
    ///   - completion: Returns the authorization details containing the signed assertion on success.
    func signInWithPasskey(challenge: Data, completion: @escaping (Result<ASAuthorization, Error>) -> Void) {
        self.completionHandler = completion
        
        // 1. Initialize the provider
        let provider = ASAuthorizationPlatformPublicKeyCredentialProvider(relyingPartyIdentifier: domain)
        
        // 2. Create the assertion (login) request
        let request = provider.createCredentialAssertionRequest(challenge: challenge)
        request.userVerificationPreference = .required
        
        // 3. Execute the authorization flow
        executeAuthorizationRequest(requests: [request])
    }
    
    // MARK: - Private Helpers
    
    private func executeAuthorizationRequest(requests: [ASAuthorizationRequest]) {
        let authorizationController = ASAuthorizationController(authorizationRequests: requests)
        authorizationController.delegate = self
        authorizationController.presentationContextProvider = self
        authorizationController.performRequests()
    }
}

// MARK: - ASAuthorizationControllerDelegate

extension PasskeyManager: ASAuthorizationControllerDelegate {
    
    /// Triggered when biometric authentication succeeds and credentials are valid.
    func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {
        
        switch authorization.credential {
        case let credentialRegistration as ASAuthorizationPlatformPublicKeyCredentialRegistration:
            // --- PASSKEY REGISTRATION SUCCESS ---
            // Extract the data required by your backend server to register the credential:
            // - credentialRegistration.rawAttestationObject
            // - credentialRegistration.credentialID
            print("Successfully registered Passkey with ID: \(credentialRegistration.credentialID.base64EncodedString())")
            completionHandler?(.success(authorization))
            
        case let credentialAssertion as ASAuthorizationPlatformPublicKeyCredentialAssertion:
            // --- PASSKEY SIGN-IN SUCCESS ---
            // Extract the data required by your backend server to verify the user signature:
            // - credentialAssertion.signature
            // - credentialAssertion.rawAuthenticatorData
            // - credentialAssertion.credentialID
            print("Successfully authenticated Passkey with ID: \(credentialAssertion.credentialID.base64EncodedString())")
            completionHandler?(.success(authorization))
            
        default:
            let unknownError = NSError(domain: "PasskeyManager", code: -1, userInfo: [NSLocalizedDescriptionKey: "Unsupported credential type generated."])
            completionHandler?(.failure(unknownError))
        }
    }
    
    /// Triggered when the operation fails or the user cancels the Face ID/Touch ID prompt.
    func authorizationController(controller: ASAuthorizationController, didCompleteWithError error: Error) {
        print("Passkey operation failed with error: \(error.localizedDescription)")
        completionHandler?(.failure(error))
    }
}

// MARK: - ASAuthorizationControllerPresentationContextProviding

extension PasskeyManager: ASAuthorizationControllerPresentationContextProviding {
    
    /// Determines the window where the Face ID / Touch ID system sheet will overlay.
    func presentationAnchor(for controller: ASAuthorizationController) -> ASPresentationAnchor {
        // Fetch the active UIWindow scene to present the native biometric sheet securely
        guard let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
              let window = windowScene.windows.first(where: { $0.isKeyWindow }) else {
            return UIWindow()
        }
        return window
    }
}
